name: Deploy to Elastic Beanstalk

# Trigger deployment on `git push` to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: EB deploy on git push main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch main
        uses: actions/checkout@v2

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        # access at ${{ steps.package-version.outputs.current-version }}

      - name: Show version number
        run: |
          echo "Package version ${{ steps.package-version.outputs.current-version }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Make build folder
        run: ./.github/scripts/build.sh

      - name: Make deploy.zip
        run: ./.github/scripts/make-deploy.sh

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name:  github-eb-demo
          environment_name: Githubebdemo-env
          version_label: ${{ github.sha }}
          region: us-west-2
          deployment_package: deploy.zip

      - name: Add aws CLI
        uses: chrislennon/action-aws-cli@v1.1

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
          -- paths /images
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
