name: Deploy to Elastic Beanstalk

# Trigger deployment on `git push` to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: EB deploy on git push main
    runs-on: ubuntu-latest

    steps:
      - name: Ckeckout branch main
        uses: actions/checkout@v1

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        # access at ${{ steps.package-version.outputs.current-version }}

      - name: Make build folder
        run: ./.github/scripts/build.sh

      - name: Make deploy folder
        run: ./.github/scripts/make-deploy.sh

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name:  github-eb-demo
          environment_name: Githubebdemo-env
          version_label: github-eb-demo-source
          use_existing_version_if_available: false
          region: us-west-2
          deployment_package: deploy.zip

